#!/bin/bash 
#BSUB -J snakemake-M04-2
#BSUB -sla CMOMEM -R highmem                                                  
#BSUB -n 2                # number of core(tasks) for parallel jobs          
#BSUB -R rusage[mem=4]    # expected resorce consumption for memory
#BSUB -W 10:00            # run time limit (hours)
#BSUB -o /home/zhangh5/work/Tapestri_project/tap_custom_SNAKEMAKE/M04-2_snakemake.stdout
#BSUB -eo /home/zhangh5/work/Tapestri_project/tap_custom_SNAKEMAKE/M04-2_snakemake.stderr

if [ -f ~/.bashrc ] ; then
    . ~/.bashrc
fi

conda activate snakemake 
cd /home/zhangh5/work/Tapestri_project/tap_custom_SNAKEMAKE
snakemake --profile lsf