#!/bin/bash 
#BSUB -J snakemake-RA16_29
#BSUB -sla CMOMEM -R highmem                                                  
#BSUB -n 4                # number of core(tasks) for parallel jobs          
#BSUB -R rusage[mem=8]    # expected resorce consumption for memory
#BSUB -W 24:00            # run time limit (hours)
#BSUB -o /home/zhangh5/work/Tapestri_project/tap_custom_SNAKEMAKE/RA16_29_snakemakev2.stdout
#BSUB -eo /home/zhangh5/work/Tapestri_project/tap_custom_SNAKEMAKE/RA16_29_snakemakev2.stderr

if [ -f ~/.bashrc ] ; then
    . ~/.bashrc
fi

conda activate snakemake 
cd /home/zhangh5/work/Tapestri_project/tap_custom_SNAKEMAKE
snakemake \
    --profile lsf \
    --conda-prefix /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/conda