username: zhangh5@mskcc.org
password: Hfhd68MdTtHn5UE
annotators: ["clinvar", "gnomad3", "chasmplus", "chasmplus_PAAD","civic","cosmic","dbsnp","dbsnp_common","clinvar","gnomad3",'thousandgenomes','go','ndex']
