# input variables for running the custom SCVarCall pipeline

top_dir: /data/iacobuzc/haochen/Tapestri_batch2/pipeline_results
scripts_dir: /data/iacobuzc/haochen/Tapestri_project/TapVarCallSmk/workflow/scripts

# ----- working directory info -----
working_dir: "default" # <------- if not default, will be set under {top_dir}

# ----- patient info -----
patient_info:
    patient_name: "RSX640"
    sample_names: ["RSX640_N"]

sample_info:
    sample_bams:
        RSX640_N: /data/iacobuzc/haochen/Tapestri_batch2/pipeline_results/RSX640/RSX640_N/tap_pipeline_output/results/bam/RSX640_N.tube1.cells.bam
    sample_rc_tsvs:
        RSX640_N: /data/iacobuzc/haochen/Tapestri_batch2/pipeline_results/RSX640/RSX640_N/tap_pipeline_output/results/tsv/RSX640_N.tube1.barcode.cell.distribution.tsv
    sample_barcode_maps:

# ----- reference files -----
reference_info:
    reference_genome: /data/iacobuzc/haochen/Tapestri_project/tapestri_pipeline_v2refs/hg19/ucsc_hg19.fa
    genome_version: hg19-ucsc
    panel_insert_file: /data/iacobuzc/haochen/Tapestri_project/panels/Tapestri-Designer-results-3359/3359.bed # <------ @HZ 04/28/2022 This is the insert.bed
    panel_insert_file_UCSC: /data/iacobuzc/haochen/Tapestri_project/panels/Tapestri-Designer-results-3359/3359.bed
    panel_amplicon_file: /data/iacobuzc/haochen/Tapestri_project/panels/Tapestri-Designer-results-3359/3359.amplicons
    panel_version: iacobuzio3359

single_sample:
    run: True
    1_split_sc_bams: True
    2_sc_mutect2_call: True
    3_filter_merge_sc_m2_call: True
    4_sc_mpileup: True
    5_write_h5: True

patient_wide:
    run: False
    1_get_candidate_alleles: True
    2_sc_mpileup: True
    3_write_h5: True

# ----- tool parameters -----
mutect2:
    # note, all supplementary database VCF files must be indexed, with .idx prefix
    # germline_resource: /home/zhangh5/work/commons/Broad-somatic-b37/af-only-gnomad.raw.sites.b37.vcf.gz
    mrpas: 0
    filterm2_ops:
        min-allele-fraction: 0.2
        unique-alt-read-count: 2

bcftools:
    BCFTOOLS_EXEC: /data/iacobuzc/haochen/Tapestri_project/TapVarCallSmk/resources/bcftools-1.15.1/bcftools
    # note the single quotation mark and the double quotation mark are seemingly not interchangeable, based on bcftools' doc
    pass1_sc_vcf_filters: ['FILTER!~"base_qual"', 'FILTER!~"low_allele_frac"', 'FILTER!~"weak_evidence"', 'FILTER!~"slippage"', 'FILTER!~"multiallelic"', 'FILTER!~"clustered_events"', 'FMT/DP>4', 'AF>0.2']
    # because sc-vcfs are normed before filtered, he multiallelic filter should do nothing
    pass1_merged_vcf_filters: ['N_PASS(GT!="mis") > 2'] # a variant needs to be individually called in at least 3 cells
    # pass2_sc_vcf_filters: ['FMT/DP>4'] # obsolete
    # pass2_merged_vcf_filters: [''] # obsolete

prev_filter_h5:
    mut_prev_threshold: 0.005
    bq_prev_threshold: 0.005