# input variables for running the custom SCVarCall pipeline

top_dir: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom
scripts_dir: /home/zhangh5/work/Tapestri_batch1/tap_custom_SNAKEMAKE/workflow/scripts

# ----- working directory info -----
working_dir: "default" # <------- if not default, will be set under {top_dir}

# ----- sample info -----
sample_info:
    # cohort_name: RA15_06
    # sample_names: ['RA15_06-14_1']

    cohort_name: Caitlin
    sample_names: ['M13-1_combined']

    # cohort_name: RA16_29
    # sample_names: ['RA16_29-16_1', 'RA16_29-24_1', 'RA16_29-25_1', 'RA16_29-32_1', 'RA16_29-47_1', 'RA16_29-2_1']
    # cohort_name: RA17_13
    # sample_names: ['RA17_13-34_1', 'RA17_13-44_1', 'RA17_13-50_1', 'RA17_13-55_1', 'RA17_13-56_1', 'RA17_13-67_1']

    # normal_pancreas:
    # batch1: ['RA17_5-14_1', 'RA17_37-39_1', 'RA17_46-20_1', 'RA18_10-30_1'] # separate into 2 again because too many variants for Mutect2 pass2
    # batch2: ['RA18_18-11_1', 'RA18_22-10_1', 'RA19_04-10_1', 'RA19_06-36_1']
# combined_cells.bam: /home/zhangh5/work/Tapestri_batch1/pipeline_results_Mutect2/autopsy/RA17_22-39_2_fresh_hg19-b37/tap_pipeline_output/results/bam/RA17_22-39_2_fresh_hg19-b37.tube1.cells.bam

# ----- reference files -----
reference_info:
    reference_genome: /home/zhangh5/work/commons/Tapestri_ref/hg19-b37/hg19-b37.fasta
    genome_version: hg19-b37
    panel_insert_file: /home/zhangh5/work/Tapestri_batch2/panel_3359/panel_3359_hg19-b37/3359.bed # <------ @HZ 04/28/2022 This is the insert.bed
    panel_amplicon_file: /home/zhangh5/work/Tapestri_batch2/panel_3359/panel_3359_hg19-b37/3359.amplicons.bed
    panel_version: iacobuzio3359


# ----- tool parameters -----

mutect2:
    # note, all supplementary database VCF files must be indexed, with .idx prefix
    germline_resource: /home/zhangh5/work/commons/Broad-somatic-b37/af-only-gnomad.raw.sites.b37.vcf.gz
    mrpas: 0
    filterm2_ops:
        min-allele-fraction: 0.2
        unique-alt-read-count: 2

bcftools:
    BCFTOOLS_EXEC: /home/zhangh5/work/Tapestri_project/tap_custom_SNAKEMAKE/resources/bcftools-1.15.1/bcftools
    # note the single quotation mark and the double quotation mark are seemingly not interchangeable, based on bcftools' doc
    pass1_sc_vcf_filters: ['FILTER!~"base_qual"', 'FILTER!~"low_allele_frac"', 'FILTER!~"weak_evidence"', 'FILTER!~"slippage"', 'FILTER!~"multiallelic"', 'FILTER!~"clustered_events"', 'FMT/DP>4', 'AF>0.2']
    pass1_merged_vcf_filters: ['N_PASS(GT!="mis") > 2'] # a variant needs to be individually called in at least 3 cells
    # pass2_sc_vcf_filters: ['FMT/DP>4']
    # pass2_merged_vcf_filters: [''] # redundant

